# call:
# ansible-playbook  -i inventory/docker/ docker-provisionning.yml
# or 
# sudo ansible-playbook  -i inventory/docker/ docker-provisionning.yml
---

- name: "create all docker images and container for all hosts listed in inventory in a dedicated network"
  hosts: localhost
  gather_facts: no

  roles:
    - { role : arnaudblancher.docker_provisionning,
      docker_provisionning_net: "ansible_myplateform" }

